debug: false
filename_google_creds: "data/credentials/patient-tracker-a176de3bd573.json"
google_sheetname: "patient_data_example"
filename_server_key: "data/credentials/server.key"
filename_server_cert: "data/credentials/server.crt"
path_sheet_data: "data/sheet_data"